#NAME: Kai Wong
#EMAIL: kaileymon@g.ucla.edu
#ID: 704451679

.SILENT: check

default: 
	gcc -pthread -o lab1a -g lab1a.c
#check: 

clean: 
	rm -f lab1a *.o *.txt  *.tar.gz

dist:
	tar -czvf lab1a-704451679.tar.gz lab1a.c Makefile README
