#NAME: Kai Wong
#EMAIL: kaileymon@g.ucla.edu
#ID: 704451679

.SILENT:

default:
	gcc -g -Wall -std=c99 lab3a.c -o lab3a

clean:
	rm -f lab3a *.tar.gz summary.csv

dist:
	tar -czf lab3a-704451679.tar.gz lab3a.c ext2_fs.h Makefile README
