#NAME: Kai Wong
#EMAIL: kaileymon@g.ucla.edu
#ID: 704451679

.SILENT:

default:
	gcc -Wall -lmraa -lm -g lab4c_tcp.c -o lab4c_tcp

clean:
	rm -f *.tar.gz *.txt lab4c_tcp lab4c_tls

dist:
	tar -czf lab4c-004611638.tar.gz lab4c_tcp.c lab4c_tls.c Makefile README 
